[package]
name = "apalis-core"
version = "0.3.0-beta.0"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Core for Apalis: simple, extensible multithreaded background processing for Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
actix = { version = "0.13", optional = true }
actix-rt = { version = "2", optional = true }
futures =  { version = "0.3", default-features = false, features=["async-await"] }
tower = { version = "0.4", optional = true, default-features = false }
pin-project-lite = "0.2.9"
tokio =  { version = "1", optional = true, default-features = false }
thiserror = "1"
log = "0.4"
http = "0.2.7"
uuid = { version = "0.8", features = ["serde", "v4"] }
strum = { version = "0.24", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
tracing-futures = { version = "0.2.5", optional = true, default-features = false }
sentry-core =  { version= "0.25.0", optional = true, default-features = false }
metrics = { version = "0.18", optional = true, default-features = false }
metrics-exporter-prometheus = { version = "0.8", optional = true, default-features = false }

[features]
default = ["trace", "actix-runtime", "tower/util", "storage", "extensions"]
storage = []
extensions = []
actix-runtime = ["actix", "actix-rt"]
sentry = ["sentry-core"]
prometheus = ["metrics", "metrics-exporter-prometheus"]
trace = ["tracing-futures/std-future", "tracing-futures/tokio"]
retry = ["tower/retry"]
timeout = ["tower/timeout"]
limit = ["tower/limit"]
filter = ["tower/filter"]

[dependencies.tracing]
default_features = false
version = "0.1"

[package.metadata.docs.rs]
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
all-features = true

