[package]
name = "actix-jobs"
version = "0.1.0"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.9"
redis = "0.15"
futures = "0.3"
serde = "1"
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
failure = "0.1"
rmp-serde = "0.14"