[package]
name = "apalis"
version = "0.3.0-beta.0"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
description = "Simple, extensible multithreaded background job processing for Rust"
repository = "https://github.com/geofmureithi/apalis"
documentation = "https://docs.rs/apalis"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["jobs", "background", "task", "actix"]
edition = "2018"

[features]
default = ["redis"]
redis = []
postgres = ["apalis-sql/postgres"]
sqlite = [ "apalis-sql/sqlite"]
mysql = [ "apalis-sql/mysql"]

[dependencies]
apalis-core = { path = "./packages/apalis-core", version = "0.3.0-beta.0" }
apalis-redis = { path = "./packages/apalis-redis", version = "0.3.0-beta.0" }
apalis-sql = { path = "./packages/apalis-sql", version = "0.3.0-beta.0" }

[dev-dependencies]
criterion = { version = "0.3", features=["async_tokio"] }
actix = "0.13"
serde = "1"
actix-rt = "2"
tokio = "1"

[[bench]]
name = "redis_benchmark"
harness = false

[workspace]
members = [
  "packages/apalis-core",
  "packages/apalis-redis",
  "packages/apalis-sql",
  # Examples
  "examples/redis",
  "examples/actix-web",
  "examples/sqlite",
  "examples/sentry",
  "examples/mysql",
  "examples/postgres",
  "examples/axum",
  "examples/prometheus",
  "examples/tracing",
  "examples/rest-api",
]