[package]
name = "apalis"
version = "0.3.0-beta.0"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
description = "Simple, extensible multithreaded background job processing for Rust"
repository = "https://github.com/geofmureithi/apalis"
documentation = "https://docs.rs/apalis"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["jobs", "background", "task", "actors", "workers"]
edition = "2018"

[features]
default = ["apalis-core/default", "tracing"]
## Include redis storage
redis = ["apalis-redis"]
## Include Postgres storage
postgres = ["apalis-sql/postgres"]
## Include SQlite storage
sqlite = [ "apalis-sql/sqlite"]
## Include MySql storage
mysql = [ "apalis-sql/mysql"]
storage = ["apalis-core/storage"]
## Support for Sentry exception and performance monitoring
sentry = ["apalis-core/sentry"]
## Support Prometheus metrics
prometheus = ["apalis-core/prometheus"]
## Support Tracing 👀
tracing = ["apalis-core/trace"]
## Support direct retrying jobs
retry = ["apalis-core/retry"]
## Support timeouts on jobs
timeout = ["apalis-core/timeout"]
## 💪 Limit the amount of jobs 
limit = ["apalis-core/limit"]
## Support filtering jobs based on a predicate
filter = ["apalis-core/filter"]
## Add a global extensions to jobs
extensions =["apalis-core/extensions"]
docsrs = ["document-features"]


[dependencies.apalis-redis]
version = "0.3.0-beta.0"
optional = true
default-features = false
path = "./packages/apalis-redis"

[dependencies.apalis-sql]
version = "0.3.0-beta.0"
optional = true
default-features = false
path = "./packages/apalis-sql"

[dependencies.apalis-core]
version = "0.3.0-beta.0"
optional = true
default-features = false
path = "./packages/apalis-core"

[dependencies.document-features]
version = "0.2"
optional = true


[package.metadata.docs.rs]
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
all-features = true


[dev-dependencies]
criterion = { version = "0.3", features=["async_tokio"] }
serde = "1"
tokio = { version = "1", features =["macros"] }

[[bench]]
name = "redis_benchmark"
harness = false

[workspace]
members = [
  "packages/apalis-core",
  "packages/apalis-redis",
  "packages/apalis-sql",
  # Examples
  "examples/email-service",
  "examples/redis",
  "examples/actix-web",
  "examples/sqlite",
  "examples/sentry",
  "examples/mysql",
  "examples/postgres",
  "examples/axum",
  "examples/prometheus",
  "examples/tracing",
  "examples/rest-api",
]