on: [pull_request]
name: Benchmark
jobs:
  storageBenchmark:
    name: Storages
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
    env:
      POSTGRES_URL: postgres://postgres:postgres@localhost/postgres
      MYSQL_URL: mysql://test:test@localhost/test
      REDIS_URL: redis://127.0.0.1/
    steps:
      - uses: actions/checkout@v3
      - uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{ github.base_ref }}
