on:
  push:
    paths:
    - 'packages/apalis-redis/**'
    - '.github/workflows/redis.yaml'
  pull_request:
    paths:
    - 'packages/apalis-redis/**'
    - '.github/workflows/redis.yaml'

name: Redis CI

jobs:
  test-redis:
    name: Test Suite Redis
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo test --features tokio-comp -- --test-threads=1
        working-directory: packages/apalis-redis
        env:
          REDIS_URL: redis://127.0.0.1/
      - run: cargo test --features async-std-comp -- --test-threads=1
        working-directory: packages/apalis-redis
        env:
          REDIS_URL: redis://127.0.0.1/
