on:
  push:
    paths:
      - "packages/apalis-sql/src/lib.rs"
      - "packages/apalis-sql/src/sqlite.rs"
      - "packages/apalis-sql/src/migrations/sqlite/**"
      - "packages/apalis-sql/src/Cargo.toml"
      - ".github/workflows/sqlite.yaml"
  pull_request:
    paths:
      - "packages/apalis-sql/src/lib.rs"
      - "packages/apalis-sql/src/sqlite.rs"
      - "packages/apalis-sql/src/migrations/sqlite/**"
      - "packages/apalis-sql/src/Cargo.toml"
      - ".github/workflows/sqlite.yaml"

name: Sqlite CI

jobs:
  test-sqlite:
    name: Test Suite Sqlite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo test --no-default-features --features sqlite,migrate,tokio-comp -- --test-threads=1
        working-directory: packages/apalis-sql
